# Generated by Django 5.0.1 on 2024-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("salery", models.IntegerField()),
                ("details", models.TextField()),
                ("available", models.BooleanField()),
                (
                    "category",
                    models.CharField(
                        choices=[("Teacher", "Teacher"), ("Student", "Student")],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
