# Generated by Django 5.0.1 on 2024-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuition", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="media/images"),
        ),
    ]
